name: flashcard_app
description: Offline AI-like Flashcard Learning App (scaffold)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  uuid: ^3.0.7
  flutter_slidable: ^2.0.0
  lottie: ^2.2.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/questions.json
    - assets/logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
  android: true
  ios: true
  android_12:
    image: assets/logo.png
    color: "#ffffff"
